"""Centralized authentication constants used to avoid hard-coded auth rules and error codes."""

MIN_PASSWORD_LENGTH = 8

AUTH_TOKEN_TYPE = "bearer"

LEGACY_USER_EMAIL = "legacy@spendsmart.internal"

ERROR_EMAIL_EXISTS = "EMAIL_ALREADY_EXISTS"
ERROR_PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
ERROR_TOKEN_EXPIRED = "TOKEN_EXPIRED"
ERROR_INVALID_TOKEN = "INVALID_TOKEN"
ERROR_UNAUTHORIZED = "UNAUTHORIZED"

__all__ = [
  "MIN_PASSWORD_LENGTH",
  "AUTH_TOKEN_TYPE",
  "LEGACY_USER_EMAIL",
  "ERROR_EMAIL_EXISTS",
  "ERROR_PASSWORD_TOO_SHORT",
  "ERROR_TOKEN_EXPIRED",
  "ERROR_INVALID_TOKEN",
  "ERROR_UNAUTHORIZED",
]
