"""Centralized non-auth business constants used across backend modules."""

from app.core.constants.analytics import (
  CATEGORY_LIMIT,
  EXPENSE_BREAKDOWN_LIMIT,
  MONTHLY_TREND_MONTHS,
  WEEKLY_LOOKBACK_DAYS,
)
from app.core.constants.messages import (
  BILL_NOT_FOUND_MESSAGE,
  BUDGET_NOT_FOUND_MESSAGE,
  GOAL_NOT_FOUND_MESSAGE,
  TRANSACTION_NOT_FOUND_CODE,
  TRANSACTION_NOT_FOUND_MESSAGE,
)
from app.core.constants.transactions import (
  DEFAULT_INCOME_CATEGORY,
  DEFAULT_INCOME_PAYMENT_METHOD,
  TX_STATUS_NOT_SUBMITTED,
  TX_STATUS_SUBMITTED,
  TX_TYPE_EXPENSE,
  TX_TYPE_INCOME,
)

__all__ = [
  "BILL_NOT_FOUND_MESSAGE",
  "BUDGET_NOT_FOUND_MESSAGE",
  "CATEGORY_LIMIT",
  "DEFAULT_INCOME_CATEGORY",
  "DEFAULT_INCOME_PAYMENT_METHOD",
  "EXPENSE_BREAKDOWN_LIMIT",
  "GOAL_NOT_FOUND_MESSAGE",
  "MONTHLY_TREND_MONTHS",
  "TRANSACTION_NOT_FOUND_CODE",
  "TRANSACTION_NOT_FOUND_MESSAGE",
  "TX_STATUS_NOT_SUBMITTED",
  "TX_STATUS_SUBMITTED",
  "TX_TYPE_EXPENSE",
  "TX_TYPE_INCOME",
  "WEEKLY_LOOKBACK_DAYS",
]
