"""Analytics query constants."""

MONTHLY_TREND_MONTHS = 6
CATEGORY_LIMIT = 8
EXPENSE_BREAKDOWN_LIMIT = 12
WEEKLY_LOOKBACK_DAYS = 14

__all__ = [
  "CATEGORY_LIMIT",
  "EXPENSE_BREAKDOWN_LIMIT",
  "MONTHLY_TREND_MONTHS",
  "WEEKLY_LOOKBACK_DAYS",
]
